config/routes.rb
Rails.application.routes.draw do


 devise_for :users,
  controllers: {  registrations: "registrations"}


  resources :wanted_concerts

  resources :concerts
  root 'concerts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concert.rb
class Concert < ApplicationRecord

  scope :last_found, -> { where("concerts.created_at >= ?", 1.second.ago ) }


  def department
    self.city[/\(.*?\)/].gsub(/[()]/, "").to_i
  end

  def city_name
    self.city[/^[^\(]+/].rstrip!
  end

  def location_name
    self.city[/\|(.*)/].gsub("|", "").strip
  end


  def date_day
    self.date[/^[0-9]{1,2}/]
  end

  def date_month
    self.date[/[a-zA-z]+/]
  end

  def date_year
    self.date[/[0-9]{4}$/]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :wanted_concerts

end

app/models/wanted_concert.rb
class WantedConcert < ApplicationRecord
  belongs_to :user
  validates :department, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  before_action :set_concert, only: [:show, :edit, :update, :destroy]

  def index
    @concerts = Concert.all
  end

  def show
  end

  def new
    @concert = Concert.new
  end

  def edit
  end

  def create
    @concert = Concert.new(concert_params)
    respond_to do |format|
      if @concert.save
        format.html { redirect_to @concert, notice: 'Concert was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end


  def update
    respond_to do |format|
      if @concert.update(concert_params)
        format.html { redirect_to @concert, notice: 'Concert was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end


  def destroy
    @concert.destroy
    respond_to do |format|
      format.html { redirect_to concerts_url, notice: 'Concert was successfully destroyed.' }
    end
  end

  private
    def set_concert
      @concert = Concert.find(params[:id])
    end

    def concert_params
      params.require(:concert).permit(:city, :date)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
   params.require(:user).permit(:nickname, :email, :password, :password_confirmtaion, :current_password)
  end

  def account_update_params
    params.require(:user).permit(:nickname, :email,  :password, :password_confirmtaion, :current_password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end

  private
   def user_params
     params.require(:user).permit(:nickname, :email, :password, :password_confirmation)
   end
end

app/controllers/wanted_concerts_controller.rb
class WantedConcertsController < ApplicationController
  before_action  :authenticate_user!
  before_action  :find_wanted_concert, only: :destroy

  def index
    @wanted_concerts = WantedConcert.where("user_id =?", current_user.id)
  end

  def new
    @wanted_concert = WantedConcert.new
  end

  def create
    @wanted_concert = WantedConcert.new(wanted_concerts_params)
    @wanted_concert.user_id = current_user.id
    if @wanted_concert.save!
      redirect_to wanted_concerts_path, notice: "Ton souhait est bien enregistré"
    else
      render :new , alert: "Oups recommence!"
    end
  end

  def destroy
    @wanted_concert.destroy
    respond_to do |format|
      format.html { redirect_to wanted_concerts_url, notice: 'Ton souhait a bien été supprimé' }
    end
  end

  private

  def find_wanted_concert
    @wanted_concert = WantedConcert.find(params[:id])
  end

  def wanted_concerts_params
    params.require(:wanted_concert).permit(:department, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  DEPARTMENTS = {
    "01" => "Ain",
    "02" => "Aisne",
    "03" => "Allier",
    "04" => "Alpes-de-Haute Provence",
    "05" => "Hautes-Alpes",
    "06" => "Alpes Maritimes",
    "07" => "Ardèche",
    "08" => "Ardennes",
    "09" => "Ariège",
    "10" => "Aube",
    "11" => "Aude",
    "12" => "Aveyron",
    "13" => "Bouches-du-Rhône",
    "14" => "Calvados",
    "15" => "Cantal",
    "16" => "Charente",
    "17" => "Charente-Maritime",
    "18" => "Cher",
    "19" => "Corrèze",
    "20" => "Corse",
    "2a" => "Corse-du-Sud",
    "2b" => "Haute-Corse",
    "21" => "Côte d'Or",
    "22" => "Côtes d'Armor",
    "23" => "Creuse",
    "24" => "Dordogne",
    "25" => "Doubs",
    "26" => "Drôme",
    "27" => "Eure",
    "28" => "Eure-et-Loire",
    "29" => "Finistère",
    "30" => "Gard",
    "31" => "Haute-Garonne",
    "32" => "Gers",
    "33" => "Gironde",
    "34" => "Hérault",
    "35" => "Ille-et-Vilaine",
    "36" => "Indre",
    "37" => "Indre-et-Loire",
    "38" => "Isère",
    "39" => "Jura",
    "40" => "Landes",
    "41" => "Loir-et-Cher",
    "42" => "Loire",
    "43" => "Haute-Loire",
    "44" => "Loire-Atlantique",
    "45" => "Loiret",
    "46" => "Lot",
    "47" => "Lot-et-Garonne",
    "48" => "Lozère",
    "49" => "Maine-et-Loire",
    "50" => "Manche",
    "51" => "Marne",
    "52" => "Haute-Marne",
    "53" => "Mayenne",
    "54" => "Meurthe-et-Moselle",
    "55" => "Meuse",
    "56" => "Morbihan",
    "57" => "Moselle",
    "58" => "Nièvre",
    "59" => "Nord",
    "60" => "Oise",
    "61" => "Orne",
    "62" => "Pas-de-Calais",
    "63" => "Puy-de-Dôme",
    "64" => "Pyrenées-Atlantiques",
    "65" => "Hautes-Pyrenées",
    "66" => "Pyrenées-Orientales",
    "67" => "Bas-Rhin",
    "68" => "Haut-Rhin",
    "69" => "Rhône",
    "70" => "Haute-Saône",
    "71" => "Saône-et-Loire",
    "72" => "Sarthe",
    "73" => "Savoie",
    "74" => "Haute-Savoie",
    "75" => "Paris",
    "76" => "Seine-Maritime",
    "77" => "Seine-et-Marne",
    "78" => "Yvelines",
    "79" => "Deux-Sèvres",
    "80" => "Somme",
    "81" => "Tarn",
    "82" => "Tarn-et-Garonne",
    "83" => "Var",
    "84" => "Vaucluse",
    "85" => "Vendée",
    "86" => "Vienne",
    "87" => "Haute-Vienne",
    "88" => "Vosges",
    "89" => "Yonne",
    "90" => "Territoire de Belfort",
    "91" => "Essonne",
    "92" => "Hauts-de-Seine",
    "93" => "Seine-Saint-Denis",
    "94" => "Val-de-Marne",
    "95" => "Val-d'Oise"
  }
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/registration_controller_helper.rb
module RegistrationControllerHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/concerts/_form.html.erb
<%= form_for(concert) do |f| %>
  <% if concert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(concert.errors.count, "error") %> prohibited this concert from being saved:</h2>

      <ul>
      <% concert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/concerts/edit.html.erb
<h1>Editing Concert</h1>

<%= render 'form', concert: @concert %>

<%= link_to 'Show', @concert %> |
<%= link_to 'Back', concerts_path %>

app/views/concerts/index.html.erb
<h1>Concerts</h1>


<ul>
  <% @concerts.each do |concert| %>
    <li><%= concert.date_day %> <%= concert.date_month %> <%= concert.date_year %> | <%= concert.city_name %> | <%= concert.department %> | <%= concert.location_name %></li>

  <% end %>
</ul>

app/views/concerts/new.html.erb
<h1>New Concert</h1>

<%= render 'form', concert: @concert %>

<%= link_to 'Back', concerts_path %>

app/views/concerts/show.html.erb
<%= @concert.date %>
<%= @concert.city %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-fixed-top navbar">
  <div class="container">
    <%= link_to "Concerts", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
       <ul>
         <% if user_signed_in? %>
           <h5>Hey <%= current_user.nickname %>!!</h5>
           <li><%= link_to "Deconnexion", destroy_user_session_path, method: :delete %></li>
           <li><%= link_to "EditProfile", edit_user_registration_path(current_user)  %></li>
           <li><%= link_to "Souhaits", wanted_concerts_path %></li>
           <li><%= link_to "Créer un souhait", new_wanted_concert_path %> </li>
         <% else %>
           <li><%= link_to "Connexion", new_user_session_path %></li>
           <li><%= link_to "Créer un compte", new_user_registration_path %></li>
           <li><%= link_to "Les Concerts", concerts_path %></li>
         <% end %>
       </ul>
      </ul>
    </nav>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ConcertDates</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render "shared/flashes" %>
    <%= render 'layouts/nav' %>
  </head>

  <body>
    <div class="container">

    <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/concert.html.erb
<h2>Salut !</h2>

<p>Les Mountain Men seront en concert à <%= concert.city %> le <%= concert.date %></p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/wanted_concerts/index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2" >
    <h2>Mes souhaits </h2>
    <ul>
      <% @wanted_concerts.each do |wanted| %>
        <li> <%= wanted.department %> <%= link_to "Supprimer", wanted_concert_path(wanted), method: :delete %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/wanted_concerts/new.html.erb
<div class="row">
  <div class=" col-md-8 col-md-offset-2 ">

    <h2>Où aimerais-tu voir les Mountain Men?</h2>
    <%= simple_form_for(@wanted_concert) do |f| %>
        <%= f.input :department, prompt: "Choisi une région", label: false, collection: ApplicationHelper::DEPARTMENTS.map { |k, v| v } %>
        <%= f.submit "Valider", class: "btn btn-success" %>
    <% end %>

  </div>
</div>